# Generated by Django 5.2.15 on 2026-06-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('participant_name', models.CharField(blank=True, max_length=255)),
                ('participant_email', models.EmailField(blank=True, max_length=254)),
                ('participant_phone', models.CharField(blank=True, max_length=20)),
                ('field_data', models.JSONField(default=dict, help_text='Dynamic responses stored as json')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TOXIQ Program Registration', max_length=200)),
                ('instructions', models.TextField(blank=True, default='Please read all instructions carefully before registration.')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.registration')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('textarea', 'Text Area'), ('number', 'Number Field'), ('email', 'Email Field'), ('phone', 'Phone Field'), ('date', 'Date Field'), ('radio', 'Radio Buttons'), ('dropdown', 'Dropdown Select'), ('checkbox', 'Checkbox list'), ('file', 'File Upload')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text', models.CharField(blank=True, max_length=200, null=True)),
                ('options', models.JSONField(blank=True, help_text="List of options for selection elements, e.g. ['Male', 'Female']", null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='Regex patterns, file limits, min/max values', null=True)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='registration.registrationform')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.registrationform'),
        ),
    ]
