# Generated by Django data migration for ToxIQ form fields sync

from django.db import migrations

def update_fields(apps, schema_editor):
    RegistrationForm = apps.get_model('registration', 'RegistrationForm')
    RegistrationField = apps.get_model('registration', 'RegistrationField')
    
    # Find active form or create one
    form = RegistrationForm.objects.filter(is_active=True).first()
    if not form:
        form = RegistrationForm.objects.create(
            title='TOXIQ 2026 Registration Form',
            instructions='Please read all instructions carefully. Upload proof of identity and select your registration category.',
            fee_amount=1000.00,
            currency='INR',
            tax_percentage=18.00,
            is_active=True
        )
    else:
        form.title = 'TOXIQ 2026 Registration Form'
        form.instructions = 'Please read all instructions carefully. Upload proof of identity and select your registration category.'
        form.fee_amount = 1000.00
        form.tax_percentage = 18.00
        form.save()
        
    # Clear existing fields for this form to prevent duplicates and rebuild order
    RegistrationField.objects.filter(form=form).delete()
    
    # Seed the fields with user requirements
    fields = [
        ('Prefix', 'dropdown', True, 'Select title', ['Mr.', 'Ms.', 'Mrs.', 'Dr.'], 1),
        ('Full Name', 'text', True, 'Enter your full name', None, 2),
        ('Email Address', 'email', True, 'Enter your email address', None, 3),
        ('Phone Number (WhatsApp)', 'phone', True, 'e.g. +91 9876543210', None, 4),
        ('Designation', 'text', True, 'Enter your designation', None, 5),
        ('Institute / Hospital', 'text', True, 'Enter your workplace/college name', None, 6),
        ('Department', 'text', True, 'Enter department name', None, 7),
        ('Specialty / Department of Practice', 'checkbox', True, None, [
            'Emergency Medicine', 'Clinical Pharmacy', 'Critical Care', 
            'General Medicine', 'Pediatrics', 'Forensic Medicine', 
            'Family Medicine', 'General practitioner', 'Others'
        ], 8),
        ('Registration Category', 'checkbox', True, None, [
            {'value': 'Invited speakers', 'price': 0.00, 'link': 'https://ease.buzz/26064ARm0a'},
            {'value': 'Specialist/Consultant', 'price': 3000.00, 'link': 'https://ease.buzz/2606sGmUAe'},
            {'value': 'Residents/General Practitioners', 'price': 2000.00, 'link': 'https://ease.buzz/2606srntA0'},
            {'value': 'Students/Interns/Nurses/Clinical Pharmacist/ Paramedics', 'price': 1000.00, 'link': 'https://ease.buzz/26069HKtYU'}
        ], 9),
        ('Medical Council Name', 'text', True, 'Enter Medical Council Name', None, 10),
        ('Registration No:', 'number', True, 'Enter Registration Number', None, 11),
        ('Food Preference', 'radio', True, None, ['Veg', 'Non-Veg'], 12),
    ]
    
    for label, ftype, req, placeholder, options, order in fields:
        RegistrationField.objects.create(
            form=form,
            label=label,
            field_type=ftype,
            is_required=req,
            placeholder=placeholder,
            options=options,
            order=order
        )

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_fields),
    ]
