# Generated by Django 5.2.15 on 2026-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_update_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_spot_registration',
            field=models.BooleanField(default=False),
        ),
    ]
