# Generated by Django 5.2.15 on 2026-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_brochure_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='registration_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
