# Generated by Django 5.2.15 on 2026-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sitesettings_registration_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
