# Generated by Django 5.2.15 on 2026-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_banner_image_alter_brochure_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cta_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
