# Generated by Django 5.2.15 on 2026-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_banner_cta_link_alter_banner_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_banner',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/'),
        ),
    ]
