# Generated by Django 5.2.15 on 2026-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_banner_image_alter_brochure_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
